include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
  plugins:
    - custom_lint